### ISSUE TITLE
error C2039: 'converts_from_string': is not a member of 'pqxx::string_traits<pgvector::Vector>'

### ISSUE THREAD

**Issue by VamshiGowdaHP** [pgvector/pgvector-cpp#3]
tried using libpqxx library for running example cpp application which is under test folder of pgvector-cpp repository - https://github.com/pgvector/pgvector-cpp

but facing error while building the project and the error looks like this

error C2065: 'converts_to_string': undeclared identifier
error C2131: expression did not evaluate to a constant
error C2039: 'converts_from_string': is not a member of 'pqxx::string_traitspgvector::Vector'
error C2065: 'converts_from_string': undeclared identifier
error C2131: expression did not evaluate to a constant

all these errors are referring to the file conversions.hxx

steps followed to install lipqxx library

.\vcpkg\vcpkg install libpqxx:x64-windows
.\vcpkg\vcpkg integrate install
.\vcpkg\vcpkg install libpqxx

and i also tried installing lipqxx from the steps given in this repo - https://github.com/GordonLElliott/Easy-PQXX-Build-for-Windows-Visual-Studio

However it gave same error in both the cases.

is there any solution to resolve this error?

**Comment by ankane** [comment]
Hi @VamshiGowdaHP, I don't think I've tried it on Windows yet. Are you able to get [this example](https://github.com/jtv/libpqxx?tab=readme-ov-file#programming-with-libpqxx) from the libpqxx readme working (without pgvector)?

**Comment by VamshiGowdaHP** [comment]
Hi @ankane, Yes. I am able to run the example from the libpqxx readme.

**Comment by ankane** [comment]
Does adding the following header fix it?

```cpp
#include <pqxx/strconv>
```

**Comment by VamshiGowdaHP** [comment]
No, its giving same error.

**Comment by ankane** [comment]
Thanks for checking. Pushed a fix in the commit above.
