### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by blueberry64** [pgvector/pgvector-cpp#5]
Hey, I can't seem to use this at all with `g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0`.  I have tried including it in my project and also compiling the test/pqxx_test.cpp.  

I get a ton of errors:
 `error: expected initializer before ‘<’ token
    6 | template <> std::string const type_name<pgvector::Vector>{"vector"};
      |                                        ^
/usr/local/include/pgvector/pqxx.hpp:8:20: error: ‘nullness’ is not a class template
    8 | template <> struct nullness<pgvector::Vector> : pqxx::no_null<pgvector::Vector> {};
      |                    ^~~~~~~~
/usr/local/include/pgvector/pqxx.hpp:8:62: error: expected template-name before ‘<’ token
    8 | template <> struct nullness<pgvector::Vector> : pqxx::no_null<pgvector::Vector> {};
      |                                                              ^
/usr/local/include/pgvector/pqxx.hpp:8:62: error: expected ‘{’ before ‘<’ token
/usr/local/include/pgvector/pqxx.hpp:27:10: error: ‘zview’ does not name a type
   27 |   static zview to_buf(char *begin, char *end, pgvector::Vector const &value) {
      |          ^~~~~
/usr/local/include/pgvector/pqxx.hpp: In static member function ‘static char* pqxx::string_traits<pgvector::Vector>::into_buf(char*, char*, const pgvector::Vector&)’:
/usr/local/include/pgvector/pqxx.hpp:33:51: error: incomplete type ‘pqxx::string_traits<std::vector<float> >’ used in nested name specifier
   33 |     auto ret = string_traits<std::vector<float>>::into_buf(
      |                                                   ^~~~~~~~
/usr/local/include/pgvector/pqxx.hpp: In static member function ‘static size_t pqxx::string_traits<pgvector::Vector>::size_buffer(const pgvector::Vector&)’:
/usr/local/include/pgvector/pqxx.hpp:42:47: error: incomplete type ‘pqxx::string_traits<std::vector<float> >’ used in nested name specifier
   42 |     return string_traits<std::vector<float>>::size_buffer(
      |                                               ^~~~~~~~~~~
ninja: build stopped: subcommand failed.`

**Comment by ankane** [comment]
Hi @blueberry64, make sure you're using `-std=c++17` or `-std=c++20` and libpqxx 7.6.0+.
